version: '3.8'

services:
  app:
    build:
      context: ./devsecops-be
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - DATABASE=${DATABASE}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./devsecops-be:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
