version: '3.8'

services:
  app:
    build:
      context: ./devsecops-be
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=your_jwt_secret
      - USER=your_db_user
      - PASSWORD=your_db_password
      - HOST=your_db_host
      - DATABASE=your_db_name
      - DB_PORT=5432
    volumes:
      - ./devsecops-be:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
